// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.


export const environment = {
  production: true,
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],

  serverUrl: 'https://localhost:7294/api',
  serverFilePath: 'https://localhost:7294/',
  // serverUrl: 'https://185.227.134.118/plesk-site-preview/api.stoic-wilbur.185-227-134-118.plesk.page/api',
  // serverFilePath: 'https://185.227.134.118/plesk-site-preview/api.stoic-wilbur.185-227-134-118.plesk.page/',
  // serverUrl: 'https://api.stoic-wilbur.185-227-134-118.plesk.page/api',
  // serverFilePath: 'https://api.stoic-wilbur.185-227-134-118.plesk.page/',
};
